(ns molehere.core
  (:require [play-cljs.core :as p]))

(def ^:const mole-width 200)
(def ^:const mole-height 170)
(def ^:const mole-image-path "images/mole.png")

(defn mole-frame [x-frame y-frame]
  [:image {:name mole-image-path :sx (* x-frame mole-width) :sy (* y-frame mole-height) :swidth mole-width :sheight mole-height}])

(def ^:const spawn [:animation {:duration 25}
                    (mole-frame 0 0)
                    (mole-frame 1 0)
                    (mole-frame 2 0)
                    (mole-frame 3 0)
                    (mole-frame 4 0)
                    (mole-frame 5 0)
                    (mole-frame 0 1)
                    (mole-frame 1 1)
                    (mole-frame 2 1)
                    (mole-frame 3 1)
                    (mole-frame 4 1)
                    (mole-frame 5 1)
                    (mole-frame 0 2)
                    (mole-frame 1 2)
                    (mole-frame 2 2)
                    (mole-frame 3 2)
                    (mole-frame 4 2)
                    (mole-frame 5 2)
                    (mole-frame 0 3)
                    (mole-frame 1 3)
                    (mole-frame 2 3)
                    (mole-frame 3 3)
                    (mole-frame 4 3)
                    (mole-frame 5 3)
                    (mole-frame 0 4)
                    (mole-frame 1 4)
                    (mole-frame 2 4)
                    (mole-frame 3 4)
                    (mole-frame 4 4)
                    (mole-frame 5 4)
                    (mole-frame 0 5)
                    (mole-frame 1 5)
                    (mole-frame 2 5)
                    (mole-frame 3 5)
                    (mole-frame 4 5)
                    (mole-frame 5 5)
                    (mole-frame 0 6)
                    (mole-frame 1 6)
                    (mole-frame 2 6)
                    (mole-frame 3 6)
                    (mole-frame 4 6)
                    (mole-frame 5 6)
                    (mole-frame 0 7)
                    (mole-frame 1 7)
                    (mole-frame 2 7)
                    (mole-frame 3 7)
                    (mole-frame 4 7)
                    (mole-frame 5 7)
                    (mole-frame 0 8)
                    (mole-frame 1 8)
                    (mole-frame 2 8)
                    (mole-frame 3 8)
                    (mole-frame 4 8)
                    (mole-frame 5 8)
                    (mole-frame 0 9)
                    (mole-frame 1 9)
                    (mole-frame 2 9)
                    (mole-frame 3 9)
                    (mole-frame 4 9)
                    (mole-frame 5 9)])

(defonce game (p/create-game 720 1280))
(defonce state (atom {}))

(def main-screen
  (reify p/Screen
    (on-show [this]
      (reset! state {:text-x 20 :text-y 30}))
    (on-hide [this])
    (on-render [this]
      (p/render game
                [[:image {:name "images/background.jpg" :x 0 :y 0 :width 720 :height 1280}]
                 [:div {:x 10 :y 400}
                  spawn]])
      (swap! state update :text-x inc))))

(doto game
  (p/start)
  (p/set-screen main-screen))
